[profile.default]
bytecode_hash = "none"
evm_version = "cancun"
ffi = true
fs_permissions = [{access = "read-write", path = ".forge-snapshots/"}, {access = "read", path = "deploy-config/"}]
libs = ["lib"]
out = "out"
optimizer = true
optimizer_runs = 44444444
solc_version = "0.8.26"
src = "src"
via_ir = false

[lint]
exclude_lints = ["screaming-snake-case-immutable", "screaming-snake-case-const"]
lint_on_build = false

[fmt] # See https://book.getfoundry.sh/reference/config/formatter
line_length = 120
bracket_spacing = true
multiline_func_header = "all"
number_underscore = "thousands"

[fuzz]
max_test_rejects = 1000000

[rpc_endpoints]
local="${LOCALHOST_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
ethereum = "${ETHEREUM_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
ethereum = { key = "${ETHERSCAN_API_KEY}" }
